### ISSUE TITLE
webpack.base.config中的getDirPath('node_modules')

### ISSUE THREAD

**Issue by baozouai** [boty-design/fe-cli#1]
[https://github.com/boty-design/fe-cli/blob/master/src/build/webpack/webpack.base.config.ts#L53](url)
中的

```typescript
{
          test: /\.(js|jsx|ts|tsx)$/,
          use: babelConfig,
          exclude: [
            [getDirPath('node_modules')], // 由于node_modules 都是编译过的文件，这里我们不让 babel 去处理其下面的 js 文件
          ]
   },
```

输出是`fe-cli/lib/util/node_modules`，这样能找到node_modules吗

**Comment by Cookieboty** [comment]
这个函数，我在方法里面添加了(../)这种，所以应该能找不到，不过已经替换成了require.resolve，你可以看下项目哈
