### ISSUE TITLE
parseVersion处理有误

### ISSUE THREAD

**Issue by baozouai** [boty-design/fe-cli#2]
![image](https://user-images.githubusercontent.com/33510001/133107484-61eb25c1-6e88-4cb6-807e-dd1eb86a9ba8.png)

paseVersion有两个问题

1. 返回的string是以`,`拼接的，函数目的应该是要处理为如'3.3.2' -> '332'
2. 版本号`3.2.2`('332')应该是小于`10.2.2`('1022')的，但实际上`'322' > '1022'`(对应字符串比较来说）
![image](https://user-images.githubusercontent.com/33510001/133108486-4eeed248-be72-40a0-b6e9-a3e57745a50f.png)

 
所以parseVersion是否应该改写为：

```ts
const parseVersion = (ver: string) => {
  return Number(ver.split('.').toString(''))
}
```

![image](https://user-images.githubusercontent.com/33510001/133108967-0c30e594-efcc-48df-a8bb-c60d56312664.png)

**Comment by Cookieboty** [comment]
已修复，感谢指正

**Comment by baozouai** [comment]
> 已修复，感谢指正

![image](https://user-images.githubusercontent.com/33510001/133391705-0fa5e639-0ccd-4f52-8cf1-20fc123667fa.png)
上次写的函数后面的toString应该改为join('')


```ts
const parseVersion = (ver: string) => {
  return Number(ver.split('.').join(''))
}
```

这才是对的
